# docker compose example
services:
  caddy:
    pull_policy: always
#    image: public.ecr.aws/sliamb/caddy:latest
    image: goer99/caddy-with-ssl:latest
    container_name: caddy-with-ssl
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - DNS=8.8.8.8,223.5.5.5
    volumes:
      - /share/Container/caddy/data:/data
    network_mode: "host"
    # Use mapping if not using host network_mode.
    # ports:
    #   - "80:80"
    #   - "443:443"
